### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by rknightuk** [DevsDoDesign/Knockoffia#1]
- [x] CrapChat
- [x] Has it blown over yet
- [x] Contacts
- [x] Phone
- [x] Messages
- [x] Snake
- [x] Timer
- [x] Clock
- [x] Calculator
- [x] Browser (#devsdodesign website)
- [x] Ringtones

**Comment by danharper** [comment]
Boo **FUCKING** YEAH

**Comment by alismith-dev** [comment]
:balloon: :tada:

**Comment by rknightuk** [comment]
![spscdw8](https://cloud.githubusercontent.com/assets/948436/8361425/0e290ea2-1b6b-11e5-979b-ac2743649d63.gif)

**Comment by 40thieves** [comment]
http://www.reactiongifs.us/wp-content/uploads/2013/08/shut_up_baby_futurama.gif

**Comment by alismith-dev** [comment]
![](http://www.reactiongifs.us/wp-content/uploads/2013/08/shut_up_baby_futurama.gif)
